title: Charcoal
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - '*.sh'
  - script/*
  - '*.rb'
  - Gemfile*
  - vendor/bundle
  - .asset-cache
kramdown:
  parse_block_html: true
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "> 1%"
  digest: false
  features:
    integrity: true
  assets:
    - branding.scss
gems:
  - jekyll-redirect-from
baseurl: '/charcoal-se.github.io'
