title: Charcoal
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - push.sh
kramdown:
  parse_block_html: true
gems:
  - jekyll-redirect-from
baseurl: 'https://j-f1.github.io/charcoal-se.github.io/'
