title: Charcoal
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - '*.sh'
  - script/*
  - '*.rb'
  - Gemfile*
  - vendor/bundle
  - .asset-cache
kramdown:
  parse_block_html: true
assets:
  features:
    integrity: true
gems:
  - jekyll-redirect-from
baseurl: '/charcoal-se.github.io'
