title: Charcoal
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - '*.sh'
  - script/*
  - '*.rb'
  - Gemfile*
  - vendor/bundle
  - .asset-cache
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - smart
    - autolink
    - lax_spacing
    - strikethrough
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "> 1%"
  assets:
    - branding.css
gems:
  - jekyll-redirect-from
  - jekyll-avatar
baseurl: //charcoal-se.org
